### ISSUE TITLE
train.rcnn.log 

### ISSUE THREAD

**Issue by wudi00** [yizt/keras-faster-rcnn#5]
I want to train the model rpn and rcnn, but I con't see the train.rcnn.log, can you tell me something about training rpn and rcnn? Thanks
Another question I new the "pascal.py" voc_path = 'E:\ObjectDetection\keras-faster-rcnn-master\opt\dataset\VOCtest_06-Nov-2007\VOCdevkit', my path, is it right?

**Comment by yizt** [comment]
@wudi00 感谢您的反馈
a) 工程代码已有改动，reademe没有同步更新，抱歉；明天会更新readme
b) 保证VOC2007在voc_path目录下；VOC2007目录下有Annotations、JPEGImages等目录

**Comment by wudi00** [comment]
感谢您的更新，我将进一步调整代码试着训练自己的数据集

**Comment by wudi00** [comment]
已经更改了voc_path，VOC2007在voc_path路径下面，但是一直有下面这个错误，
[Errno 2] No such file or directory: '/opt/dataset/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'
[Errno 2] No such file or directory: '/opt/dataset/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/ImageSets/Main/test.txt'
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    main(argments)
  File "train.py", line 62, in main
    dataset.prepare()
  File "/media/disk/wudi/faster/faster_rcnn/preprocess/input.py", line 45, in prepare
    img_info_list, classes_count, class_mapping = get_voc_data(self.voc_path, self.class_mapping)
  File "/media/disk/wudi/faster/faster_rcnn/preprocess/pascal_voc.py", line 78, in get_voc_data
    annots = [os.path.join(annot_path, s) for s in os.listdir(annot_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dataset/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007/Annotations'
叫我检查过了，报错的文件已经存在了，请问这是怎么回事啊
