### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wudi00** [yizt/keras-faster-rcnn#6]
代码运行过程中一直出现这个错误，请问怎么解决呢？
`Traceback (most recent call last):
  File "train.py", line 121, in <module>
    main(argments)
  File "train.py", line 113, in main
    callbacks=get_call_back())
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training_generator.py", line 68, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
`

**Comment by yizt** [comment]
@wudi00 您好，应该不会出现这个错，validation_steps已经给值了
                    `validation_steps=len(test_img_info) // config.BATCH_SIZE,`

**Comment by wudi00** [comment]
这里输出test_image_info是0，但是在test.txt文件里是有数据的
`train_img_info:5011
test_img_info:0
`

**Comment by wudi00** [comment]
这里输出test_image_info是0，但是在test.txt文件里是有数据的
`train_img_info:5011
test_img_info:0
`
请问是这里的问题吗？

**Comment by wudi00** [comment]
这两个值的输出结果是正确的吗，test_img_info的输出为0，但是test.txt里面有数据啊，请问这个是怎么回事？
`train_img_info:5011
test_img_info:0
`

**Comment by wudi00** [comment]
问题解决了，是我的疏忽造成的错误，感谢您的分享！
