### ISSUE TITLE
在train.py中 m = models.frcnn(config, stage='train') 这一行报错

### ISSUE THREAD

**Issue by bendaxi** [yizt/keras-faster-rcnn#8]
您好,我用这个训练自己的图片,图片大小都改为了1280*1280,config.py中的参数也改了,在运行train.py 文件时遇到了下面的错误,通过打断点发现,传给faster_rcnn/layers/base_net.py中resnet50_head(features)函数的参数是空的,也就是**features=Tensor("roi_align/roi_align_output:0", shape=(?, ?, ?, ?, ?), dtype=float32)**,然后导致最终的错误.找了很久,不知道应该改哪里,希望您能解答一下.

Traceback (most recent call last):
  File "/Faster RCNN/train.py", line 132, in <module>
    main(argments)
  File "/Faster RCNN/train.py", line 80, in main
        **_m = models.frcnn(config, stage='train')_**
  File "/Faster RCNN/faster_rcnn/layers/models.py", line 135, in frcnn
        **fc_layers_size=config.RCNN_FC_LAYERS_SIZE)**
  File "/Faster RCNN/faster_rcnn/layers/models.py", line 207, in rcnn
        **shared_layer = head_fn(x)**
  File "/Faster RCNN/faster_rcnn/config.py", line 159, in head_fn
        **return resnet50_head(\*args, \*\*kwargs)**
  File "/Faster RCNN/faster_rcnn/layers/base_net.py", line 54, in resnet50_head
        **_x = conv_block_5d(x, 3, [filters, filters, filters \* 4], stage=5, block='a', strides=(2, 2))_**
  File "/Faster RCNN/faster_rcnn/layers/base_net.py", line 328, in conv_block_5d
        **name=conv_name_base + '2a')(input_tensor)**
  File "/home/hky/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
        **self._maybe_build(inputs)**
  File "/home/hky/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
        **self.build(input_shapes)**
  File "/home/hky/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 216, in build
        **self.layer.build(tuple(child_input_shape))**
  File "/home/hky/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 153, in build
        **raise ValueError('The channel dimension of the inputs '**
**ValueError: The channel dimension of the inputs should be defined. Found `None`.**

**Comment by yizt** [comment]
@bendaxi 请问您修改了哪些配置？

**Comment by bendaxi** [comment]
config.py中,改动后如下,(行数为github上对应的部分,代码对齐就请忽略吧,这里格式不好调)
11行: IMAGE_MAX_DIM = 1280
61行: IMAGE_PER_GPU = 16

99行: 
    	
    	class DataConfig(Config):
    	NUM_CLASSES = 1 + 1  #
    	POST_NMS_ROIS_INFERENCE = 300
    	CLASS_MAPPING = {'bg': 0,    #背景
                     	'pineapple': 1
                     	}
    	data_path = '/home/hky/folder/pineapple data/train'
    	pretrained_weights = None

144行:


    	
    	class ResnetConfig(DataConfig):
    	NAME = "pineapple"
    	BASE_NET_NAME = 'resnet50'
    	GPU_COUNT = 1
    	IMAGES_PER_GPU = 16
    	IMAGE_MAX_DIM = 1280
    	LEARNING_RATE = 0.003
    	RPN_NMS_THRESHOLD_TRAINING = 0.9
    	RPN_NMS_THRESHOLD_INFERENCE = 0.9
    	# TRAIN_LAYERS = r"(res3.*)|(bn3.*)|(res4.*)|(bn4.*)|(res5.*)|(bn5.*)|(rcnn\_.*)|(rpn\_.*)"
    	TRAIN_LAYERS = r"(res3.*)|(res4.*)|(res5.*)|(rcnn\_.*)|(rpn\_.*)"
    	# TRAIN_LAYERS = r".*"
    	RPN_TRAIN_ANCHORS_PER_IMAGE = 80
    	POOL_SIZE = (14, 14)

    	# RPN_ANCHOR_HEIGHTS = [76.01, 137.64, 210.27, 249.25, 350.94, 386.97, 546.33, 631.71, 707.87]
    	# RPN_ANCHOR_WIDTHS = [59.84, 192.22, 98.73, 358.32, 696.61, 195.61, 348.98, 891.01, 566.18]
    	RPN_ANCHOR_HEIGHTS = [52.42, 85.64, 143.89, 186.92, 208.26, 266.1, 359.72, 446.26, 484.92]
    	RPN_ANCHOR_WIDTHS = [40.85, 132.84, 66.24, 294.26, 135.53, 533.3, 190.26, 339.55, 591.88]

    	USE_HORIZONTAL_FLIP = True
    	USE_RANDOM_CROP = True

        BASE_NET_NAME = 'resnet50'

    	def base_fn(self, *args, **kwargs):
        	return resnet50(*args, **kwargs)

    	def head_fn(self, *args, **kwargs):
       		return resnet50_head(*args, **kwargs)

    	pretrained_weights = '/home/hky/folder/pineapple data/FasterRCNN model/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

192行: current_config = ResnetConfig()

**Comment by yizt** [comment]
@bendaxi 您好，没有发现配置错误，估计是系统版本问题；以下是我的环境主要包版本，python 是3.6
scikit-image 0.13.0
scikit-learn 0.20.3
scipy 1.1.0
Keras 2.2.4
numpy 1.15.0
tensorboard 1.9.0
tensorflow-gpu 1.9.0

另外：建议您先跑`python gt_cluster.py` 聚类获得合适的anchor尺寸；anchors尺寸与输入图像尺寸和GT大小相关

**Comment by bendaxi** [comment]
好的,谢谢,应该是系统版本的问题,我直接用您的config.py 跑也会出这个错误.

**Comment by 836304831** [comment]
@bendaxi 你这个问题我也碰到过，这个问题发生在RoiAlign层之后调用resnet50_head时发生的。使用keras2.2.4的版本去运行这个代码，keras内部有一个_keras_shape字段（可以通过调试查看），这个字段记录了真实推断出来的输入大小，而我们看到的shape是（none,none, none, none,none）。

本人猜测你的问题可能是：
1. 你用的keras版本比较旧，没有内部推断shape的功能，所以输入的大小无法推断出来，导致发生上面的错误。
2. 使用了tf.keras版本实现，tf.keras版本是没有_keras_shape字段的，所以没法进行有效的推断实际shape大小。

解决方案：
我们在resnet50_head看到的输入是（none,none,none,none,none），通过keras2.2.4的版本调试发现，在训练阶段，resnet50_head输入的shape是（none, 128, 14,14, 1024），在测试阶段resnet50_head的输入大小是（none， 300， 14，14，1024），那么只需要在训练接测试阶段分别设置这部分的shape大小，根据设置的shape大小进行reshape即可，如可以在resnet50_head函数中加上reshape的操作，如下：
![image](https://user-images.githubusercontent.com/8056281/60694392-9b946e80-9f10-11e9-9d84-13bfbcd46d8c.png)，该问题可以得到解决。

**Comment by bendaxi** [comment]
您说的一点都不错 @836304831 ，我当时就是用的tf.keras才导致这个错误，后来装了keras后就解决问题了。多谢。
